GET http://localhost:3001

###
POST http://localhost:3001/user/register
Content-Type: application/json

{
  "email": "ERIEgin@gmail.com",
  "password": "abc123"
}

###
POST http://localhost:3001/user/refresh-token

###
POST http://localhost:3001/user/login
Content-Type: application/json

{
  "email": "ERIEgin1@gmail.com",
  "password": "abc1234"
}

###
POST http://localhost:3001/user/logout