###
POST http://localhost:4000/money-transaction/user
Content-Type: application/json

{
  "userId": "111",
  "amount": 50
}


###
POST http://localhost:4000/money-transaction/transfer
Content-Type: application/json

{
  "fromId": "111",
  "toId": "222",
  "amount": 40
}