GET http://localhost:4000

###
POST http://localhost:4000/user/register
Content-Type: application/json

{
  "email": "ERIEgin@gmail.com",
  "password": "abc123"
}

###
POST http://localhost:4000/user/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2UwZDI5ZmY5OTdjMjQ5MzZhMzYwMGIiLCJpYXQiOjE2NzU3NTgzNDYsImV4cCI6MTcwNzMxNTk0Nn0.aRvXr5FImQQ8SDYmt9hcFkvVhk29Z1LWpEq8zwWTaZE"
}

###
POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "eriegin@gmail.com",
  "password": "abc123"
}

###
DELETE http://localhost:4000/user/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2UwZDI5ZmY5OTdjMjQ5MzZhMzYwMGIiLCJpYXQiOjE2NzU3NTg5NDQsImV4cCI6MTcwNzMxNjU0NH0.dmHBAaVmho8WvMe5_7R_n5tzYCrNVpInw7PItYCSVeI"
}

###
GET http://localhost:4000/user/getlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2UwZDI5ZmY5OTdjMjQ5MzZhMzYwMGIiLCJpYXQiOjE2NzU3NTYwNDgsImV4cCI6MTY3NTc1NjA2OH0.AhBVklyR59HJr4T0U6JkbTYfcr7DqoM_jqlpN-uJCzc
